# Generated by Django 4.1 on 2022-08-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.TextField(default='http://www.clipartbest.com/cliparts/LTK/Aa5/LTKAa55Ta.jpeg'),
        ),
    ]
